package commands;

public enum CommandType {
    AUTHORIZATION,
    FULL_LIST_USERS,
    DELETE_USER,
    ADD_USER,
    GET_CLOTHES,
    MINES_CLOTHES,
    REQUEST_CLOTHES,
    REQUEST_BUDGET,
    GET_ID,
    GET_BUDGET,
    GET_REQUEST_BY_ID,
    SET_STATE_REQUEST,
    UPDATE_USER_ACCESS,
    GET_REQUESTS_WITH_STATE_PENDING,
    SET_NEW_REQ_HISTORY,
    GET_TOTAL_PRICE_CLOTHES,
    ADD_BUDGET,
    SAVE_FINANCIAL_HISTORY,
    BACK_CLOTHES,




}
